services:
  postgres:
    image: postgres:16-alpine
    container_name: budget-postgres
    environment:
      POSTGRES_DB: budgetdb
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budgetdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: budget-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@budget.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - budget-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  budget-network:
    driver: bridge